### ISSUE TITLE
Cube texture => XR

### ISSUE THREAD

**Issue by mkeblx** [immersive-web/webxr-samples#11]
Modify cube sea texture: WebVR text => WebXR?
https://github.com/immersive-web/webxr-samples/blob/master/media/textures/cube-sea.png

**Comment by toji** [comment]
I'd like to get a whole new WebXR logo at some point. ;)

**Comment by mkeblx** [comment]
Or that :) I await your design.

**Comment by toji** [comment]
Partially fixed: Replaced many cube-sea scenes with something prettier and less logo-y. 😉
