### ISSUE TITLE
VR support not detected

### ISSUE THREAD

**Issue by rpatel11-rbp** [immersive-web/webxr-samples#131]
I cloned webxr-samples and tried to run the project in chrome. But I got message like "VR support not detected" on the front page, so can you please provide the proper steps to build and run the project with VR support in chrome.

**Comment by AdaRoseCannon** [comment]
Are you using https?

**Comment by rpatel11-rbp** [comment]
![image](https://user-images.githubusercontent.com/77781724/136924273-e04202d9-43aa-44db-ac4c-752aee2019cc.png)

**Comment by rpatel11-rbp** [comment]
![image](https://user-images.githubusercontent.com/77781724/136932314-421d197a-965d-4625-8197-f531c9b98cd1.png)
I have not found package.json file from this directory structure. So how can I run a local HTTP server, Is there any way to run an HTTP server and local host?

**Comment by AdaRoseCannon** [comment]
you don't need a package.json, just use your http-server of choice. Assuming you have npm/npx try this:
https://www.npmjs.com/package/http-server

It appears you are using Chrome so if you want a browser extension method instead try this: https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en
