### ISSUE TITLE
A blinking bug on pause video in WebXR Layers

### ISSUE THREAD

**Issue by takafumi-ko** [immersive-web/webxr-samples#150]
[This bug seen in Layers Sample / 6.Media Layer]
There is a shaking on pausing video in WebXR Layers (like on clipped video below).
The shaking problem seems to be caused by the video buffer.

https://user-images.githubusercontent.com/31178211/167344267-9b44573f-d0ff-4175-937b-29b75c776f0c.mp4

On OculusQuest2 MetaBrowser 21.0

And the Media Layer sample hard to reproduce the bug.
Please use this repository or commit to reproduce.
https://github.com/takafumi-ko/webxr-samples/commit/9abd388e2f0c2ddb1fecc859d6ec24ddc46331c8

**Comment by cabanier** [comment]
very cool! We must not be drawing into the swapchain when the video is paused.

**Comment by cabanier** [comment]
Thanks for reporting. A fix will land in 22.1

**Comment by takafumi-ko** [comment]
Thanks!
