### ISSUE TITLE
Immersive AR does not work on the Samsung browser

### ISSUE THREAD

**Issue by Jamedie** [immersive-web/webxr-samples#172]
I opened an issue in the main WebXR GitHub repository, but it seems it wasn't the right place, so I'm trying here
I tested my project on a Samsung browser and encountered a compatibility error.
When I returned to the sample, I experienced the same behavior.
This was tested on both a Galaxy S20 5G and a Galaxy S10, both running Android 13.

**Comment by Yonet** [comment]
Hi @Jamedie sounds like you need to file an issue on Samsung browser.
