### ISSUE TITLE
tips on creating gtlfs for the viewers

### ISSUE THREAD

**Issue by KevinAquino** [immersive-web/webxr-samples#188]
Hi,
I would like to create some gltfs to use in your examples but I can't seem to save them correctly - is there guidance on what the gltfs need?

For instance if I take the space.gltf file, load and save it (like in the python script below)

``` python
from pygltflib import GLTF2
gltf = GLTF2().load(filename)
gltf.save()
```

and set that output, I get an error on loading. Specifically in the web console I get:
```Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'scene.nodes')```

so obviously there are specific tags/workflows I am missing. Any advice would be great, thanks!

**Comment by AdaRoseCannon** [comment]
This is not the best place to ask these sorts of issues.

Try stackoverflow for python support.

**Comment by KevinAquino** [comment]
Hi,

Sorry this is not really a python question - more of a question on the requirements of the gltf. Is there a standard or a validator for the gltfs that can be used with the tools used here?
