### ISSUE TITLE
AR Samples not working

### ISSUE THREAD

**Issue by Bradley-Newman-RF** [immersive-web/webxr-samples#25]
- Pixel XL 1
- Android P
- Chrome Canary with WebXR flags enabled.

Behavior:
- Load this page: https://immersive-web.github.io/webxr-samples/proposals/phone-ar.html
- Press 'Start AR'
- Grant access to camera.
- Button shows 'Exit AR' but nothing else, no camera view appears.

What are the requirements for these samples?

**Comment by brianpeiris** [comment]
I reported this a a chromium bug a couple of weeks ago: https://bugs.chromium.org/p/chromium/issues/detail?id=918375

The response was that the WebXR API in Canary has changed and the samples have not been updated yet. The samples still work in Chrome Dev though.

**Comment by dobi01** [comment]
Now the samples don't work in Chrome Dev too. 
For me last working version was Chrome Dev 73.0.3643.0.

**Comment by Rosehart** [comment]
Samples also don't work on Edge for HoloLens.

**Comment by jsantell** [comment]
Spec is undergoing lots of change. I doubt these samples will consistently work anywhere for the next few weeks/months

**Comment by dmarcos** [comment]
Changes made its way to m73 and WebXR is broken at the moment including webxr samples. Moving discussion to https://github.com/immersive-web/webxr-samples/issues/35

**Comment by formatCvt** [comment]
not working on Google Pixel 3 XL in Chrome 74.0.3729.149 Android 10

**Comment by aidinabedi** [comment]
Now the samples don't seem to work in any chrome version (stable, beta, dev or canary).

**Comment by klausw** [comment]
@toji , please see the proposed fix in https://github.com/immersive-web/webxr-samples/pull/39 . Test page with that patch applied is at https://klausw.github.io/webxr-samples/proposals/phone-ar.html .

Note that you need to enable two options in chrome://flags to make this work, **WebXR Device API** and **WebXR AR Module**. The AR-specific additional flags such as Hit Test and Plane Detection no longer enable the AR module as a side effect.

**Comment by klausw** [comment]
@aidinabedi The phone-ar sample should now work again on Chrome Canary.

**Comment by zim32** [comment]
AR not working for me. Xiaomi mi a1. Chrome 87.0.4...  Android 9

**Comment by dmarcos** [comment]
@zim32 Do you know if your device is ARCore compatible? I don't see your specific phone in the [Android docs](https://developers.google.com/ar/discover/supported-devices#android_china) but not if it's up to date. Good luck

**Comment by zim32** [comment]
> @zim32 Do you know if your device is ARCore compatible? I don't see your specific phone in the [Android docs](https://developers.google.com/ar/discover/supported-devices#android_china) but not if it's up to date. Good luck

Yeah, seems to be not ARCore compatible. Thanks for quick response
