### ISSUE TITLE
Enter vr not work ! why it go to WMR? nwjs app

### ISSUE THREAD

**Issue by djmisterjon** [immersive-web/webxr-samples#52]
why when i click on enter vr, the WMR open but not with the VR sample ?
Do i miss something, am new in vr dev and am learning, sorry if is a noob question!
![image](https://user-images.githubusercontent.com/24865815/70612728-7c8fbc00-1bd5-11ea-9dbf-3f0eff93f2cc.png)
I try run this with a **samsung odyssey+**
The debugging and app session work fine, but i can see sample in vr headset.
Any help or tips are welcome.

i currently use the `nwjs SDK` with chromium engine 79.0.3
![image](https://user-images.githubusercontent.com/24865815/70614576-c1692200-1bd8-11ea-8384-16cb51942c55.png)

**Comment by djmisterjon** [comment]
Hoooo oki, you need start WMR before click button.
So if you click on open VR without WMR , the app no map automatically.!
So solution is alway keep Vr active before debug.
From what i know, must game no need to do this, it specific to webXR only ?

**Comment by klausw** [comment]
@djmisterjon , this GitHub repository and issue tracker are specifically for developing the WebXR specification and addressing issues related to the specification itself. Specific implementations are out of scope for this.

Please use other resources such as an nwjs issue tracker, or https://crbug.com for Chromium issues that can be reproduced in the browser itself apart from nwjs. Or try other community resources such as stackoverflow. (Normally I'd recommend the WebVR slack, but that doesn't currently allow others to sign up, and nobody seems to know how to fix it.)

**Comment by djmisterjon** [comment]
Yes i ask also on other resources: `nwjs,electron github` and also on Discord `virutal reality` but nobody seem know what happened here! Most dev on unity 3d game...

Hum for Slack is not a public resource, you need get invitation by a member ,
this avoids spammer overflow as on Discord, but am interesting if you're a member and can invite me.
Or if you know a official public discord for webVR and webXR dev.

I will also try stackoverflow it a good idea, I did not know there were Webvr developers there.

You can close the issue if you have no more information.
thank for you time and sorry for the mistake.
