### ISSUE TITLE
Add support for 180-degree stereo

### ISSUE THREAD

**Issue by richardtallent** [immersive-web/webxr-samples#53]
I'd love to make a web page to share photos I've taken with my 180x180 stereo camera using WebXR, so I've been trying to adapt the 360 photo example for this use case.

I was able to add support for stereoRightLeft, since I've reversed some of my 180 L/R images to allow for cross-eye viewing, but my attempts to stretch the image across only one hemisphere have failed.

Could someone who groks the vertex math here rig up an extra mode for this in skybox.js? I'd be more than happy to provide a test image under the same license.

**Comment by richardtallent** [comment]
*Update:* I've *almost* got it working! One of my L/R 180x180 photos looks fine, but a R/L 180x180 from the same camera but processed a different way has some curving at the edges.

The test files are from the Insta360 EVO, which unfortunately broke. They're just family photos, so nothing useful for a real demo. I have a new 180x180 stereo VR camera (Vuze), my next step is to create a suitable demo image (the ones I'm playing with now are family photos) and submit a PR.

Considering that 180 stereo VR cameras are now very affordable for consumers, I'm hoping this will be a practical demo to add. It's actually been a pain to share anything from these cameras with friends, so being able to do it via a simple web page and have it work on most VR systems, including cardboard, would be awesome.

**Comment by Syavick** [comment]
> I'd love to make a web page to share photos I've taken with my 180x180 stereo camera using WebXR, so I've been trying to adapt the 360 photo example for this use case.
> 
> I was able to add support for stereoRightLeft, since I've reversed some of my 180 L/R images to allow for cross-eye viewing, but my attempts to stretch the image across only one hemisphere have failed.
> 
> Could someone who groks the vertex math here rig up an extra mode for this in skybox.js? I'd be more than happy to provide a test image under the same license.

You can make 360° stereo photos in Insta360 Studio from your 180° stereo photos. Back part of photo will be black.
P.S. Have same idea to make some kind of gallery to view photos from my Insta360 Evo from web on Oculus Quest.

**Comment by richardtallent** [comment]
Following up... looks like this project is basically abandoned, so I switched over to using BabylonJS earlier this year, and that has allowed me to get both 180 VR stereo and traditional stereographs to show up properly in WebXR.
