### ISSUE TITLE
Error running hit-box sample

### ISSUE THREAD

**Issue by andypotato** [immersive-web/webxr-samples#60]
Running the hit-box sample in Chrome 79 throws the following error:
```
The provided value 'immersive-ar' is not a valid enum value of type XRSessionMode.
```
On Safari / IOS 13 no error is thrown but
```
navigator.xr.isSessionSupported('immersive-ar')
```
returns `false`

I tried both systems with and without using the polyfill.

Is this the expected behavior?

**Comment by klausw** [comment]
Please see https://immersiveweb.dev/#supporttable and the additional details linked there. In Chrome, `immersive-ar` is currently only supported on ARCore-compatible Android devices, and you need to enable "WebXR AR Module" and "WebXR Hit Test" in chrome://flags for Chrome 79 and 80. (These are planned to be enabled by default in Chrome 81, currently in beta.)

To the best of my knowledge, there's no Safari/iOS support at this time, and there isn't a polyfill that supports AR mode.

**Comment by andypotato** [comment]
Thanks for the link - Seems we won't be able to use this on IOS in the near future. It works fine though when testing on a Huawei Honor 20i, quite impressive!
