### ISSUE TITLE
Hit test is not on working on Chrome 80 on Arcore support Android device

### ISSUE THREAD

**Issue by Sanna709** [immersive-web/webxr-samples#67]

**Comment by klausw** [comment]
Please try Chrome Beta (81) where hit test is enabled by default - in Chrome 80, it needs to be enabled manually in chrome://flags.

**Comment by Sanna709** [comment]
I have tried in chrome beta as well but there No sample of webxr is working

**Comment by ybinstock** [comment]
I'm having the same issue. The barebone example (18) and immersive AR sessions (2) work fine, but the hit test example does not. When I click 'Start AR, I get the attached error. 
<img width="1109" alt="Screenshot 2020-04-14 at 11 04 48" src="https://user-images.githubusercontent.com/8645066/79206570-cddbe080-7e3f-11ea-957b-a1a64a3ee278.png">


I'm on Chrome 80.0 with hit test flag set to true, Android 10, Samsung Galaxy 9.

**Comment by klausw** [comment]
Hit test was not enabled by default in Chrome 80, so it only worked when enabled in flags. If I remember right, the feature name was not recognized yet in that version, so marking it required would fail.

Please try Chrome 81 or newer.

**Comment by ybinstock** [comment]
With the update to Chrome 81, I can now say this issue is no longer broken. 

Thanks!

**Comment by klausw** [comment]
Thanks! Closing this issue, please follow up separately if Chrome 81 or higher are still not working.
