### ISSUE TITLE
Hit test takes a long time to get ready

### ISSUE THREAD

**Issue by killerfrienddk** [immersive-web/webxr-samples#72]
Title, i do not know what is wrong but it can take up to 2-3 mins for it to start working.
Using a samsung galaxy 7

**Comment by bialpio** [comment]
This certainly does not seem right. Can you provide more details about the behavior that you are seeing? Is this a hit test subscription promise that takes a long time to resolve but then the results are available (& non-empty in subsequent frames), or are the results consistently empty (but the promise resolves quickly), or both? Are there any error messages in the console?

**Comment by killerfrienddk** [comment]
> This certainly does not seem right. Can you provide more details about the behavior that you are seeing? Is this a hit test subscription promise that takes a long time to resolve but then the results are available (& non-empty in subsequent frames), or are the results consistently empty (but the promise resolves quickly), or both? Are there any error messages in the console?

Seems like it was my carpet that was bad for tracking, kinda weird since most other trackers i have tested worked fine on it.
