### ISSUE TITLE
Example 17: "Hands Test" is missing

### ISSUE THREAD

**Issue by bmitchinson** [immersive-web/webxr-samples#80]
Would love to help update the link to example 17 but can't seem to find it anywhere? Has this example been removed?

Ref: https://cabanier.github.io/webxr-samples/ # 17

**Comment by Yonet** [comment]
@bmitchinson, we need to add a new hand example. Feel free to make a pull request if you have it. Thanks!

**Comment by bmitchinson** [comment]
Sounds good I'll take a look, maybe in the mean time we could at least mark examples that don't exist with a note?

**Comment by Yonet** [comment]
I just noticed the example you are looking for is not on immersive-web examples because it is on here: https://github.com/cabanier/webxr-samples.
For the Immersive-web samples on this repo: https://immersive-web.github.io/webxr-samples/

**Comment by cabanier** [comment]
The hands test is on the main samples page: https://immersive-web.github.io/webxr-samples/immersive-hands.html
