### ISSUE TITLE
Issue with Docker NGINX Server ?

### ISSUE THREAD

**Issue by fabioborsoi** [immersive-web/webxr-samples#81]
Dear Team, 

in order to move my fisrt step into WebXr I decide to copy the code into a plain vannila NGINX server running in my Windows 10 Host.
I'm able to reach index.html and all the other file using http://MyIP/webxr-samples/ , but it can recognize my Frefox on Quest .
I dont have any issue with the path https://immersive-web.github.io/webxr-samples/
I hope it is a docker/nginx configuration.

Any suggestion, help ?

Thanks , Fabio

**Comment by klausw** [comment]
WrbXR requires a secure origin, you need to use https:// .

**Comment by fabioborsoi** [comment]
Thanks.
FYI it works also with a selsigned certificate, on a static IP ( without a domain name )

**Comment by Yonet** [comment]
@fabioborsoi sounds like your issue is resolved. Closing the issue. Thanks!
